# Generated by Django 5.2.6 on 2026-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
